apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: autonomous-db
  labels:
    provider: opentofu
    type: autonomous-database
spec:
  compositeTypeRef:
    apiVersion: oci-resources.org/v1alpha1
    kind: AutonomousDatabase
  resources:
    - name: workspace
      base:
        apiVersion: opentofu.upbound.io/v1beta1
        kind: Workspace
        spec:
          forProvider:
            module: git::https://github.com/PZoli98/terraform-modules.git//autonomous_db?ref=main
            source: Remote
            env: [] # We'll patch these below
          providerConfigRef:
            name: opentofu-providerconfig
          writeConnectionSecretToRef:
            name: autonomousdb-connection
            namespace: default
      patches:
        - type: CombineFromComposite
          toFieldPath: "spec.forProvider.env"
          combine:
            strategy: string
            variables:
              - fromFieldPath: "spec.adminPasswordSecretRef.name"
                name: name
              - fromFieldPath: "spec.adminPasswordSecretRef.key"
                name: key
              - fromFieldPath: "spec.adminPasswordSecretRef.namespace"
                name: namespace
              - fromFieldPath: "spec.compartmentId"
                name: compartmentId
              - fromFieldPath: "spec.dbName"
                name: dbName
              - fromFieldPath: "spec.displayName"
                name: displayName
              - fromFieldPath: "spec.workload"
                name: workload
              - fromFieldPath: "spec.licenseModel"
                name: licenseModel
              - fromFieldPath: "spec.whitelistedIps"
                name: whitelistedIps
            string:
              fmt: |
                [
                  {
                    "name": "TF_VAR_admin_password",
                    "secretKeyRef": {
                      "name": "%s",
                      "key": "%s",
                      "namespace": "%s"
                    }
                  },
                  { "name": "TF_VAR_compartment_id", "value": "%s" },
                  { "name": "TF_VAR_db_name", "value": "%s" },
                  { "name": "TF_VAR_display_name", "value": "%s" },
                  { "name": "TF_VAR_db_workload", "value": "%s" },
                  { "name": "TF_VAR_license_model", "value": "%s" },
                  { "name": "TF_VAR_whitelisted_ips", "value": "%s" }
                ]
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.namespace"
          toFieldPath: "spec.writeConnectionSecretToRef.namespace"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.displayName"
          toFieldPath: "metadata.name"

